### ISSUE TITLE
Revise component to make it usable with ESP8266

### ISSUE THREAD

**Issue by ma-ef** [AzonInc/ESPHome_tcs_intercom#19]
I used the component successfully with commit on a Wemos D1 Mini (ESP8266 based) but since commit [3d7d10fd13d2f187e57c5a22d1d2c583b1f444b7](https://github.com/AzonInc/ESPHome_tcs_intercom/commit/3d7d10fd13d2f187e57c5a22d1d2c583b1f444b7) (when reference to esp_efuse.h was added) it does not work any more. Could you make those things dependent on the architecture the component is compiled for?

**Comment by AzonInc** [comment]
Please try the new component (see #18), this one is not maintained anymore.

**Comment by AzonInc** [comment]
I will close this as the new component supports both platforms.
